import ctypes
import numpy as np
import os

lib_path = os.path.abspath("maze_genc.dll") 
maze_lib = ctypes.CDLL(lib_path)

def generate_maze(size):
    final_size = 2 * size - 1
    
    # Dùng int32 vì tương ứng với 'int' trong C++
    maze_buffer = np.zeros((final_size, final_size), dtype=np.int32)
    
    # Khai báo kiểu đối số cho hàm C++
    # arg1: con trỏ mảng, arg2: số nguyên kích thước
    maze_lib.generate_maze_cpp.argtypes = [
        np.ctypeslib.ndpointer(dtype=np.int32), 
        ctypes.c_int
    ]
    
    maze_lib.generate_maze_cpp(maze_buffer, size)
    
    return maze_buffer

if __name__ == "__main__":
    gen_size = 3
    maze = generate_maze(gen_size)
    
    print("Maze generated by C++:")
    print(maze)
    
    np.savetxt("mazefinal.txt", maze, fmt="%d", delimiter=" ")